import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import Providers from "./redux/provider";
import styles from "./scss/style.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.inner}>
        <Providers>
          <Header />
          <main id="main">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
